name: postman-api-test

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "8842076-59400164-ddb8-4fc6-8f3e-017e6c08775f" --integration-id "152564-${{ github.run_id }}"
          # Lint your API using Postman CLI
          # postman api lint 115aef56-ba2b-43ec-a9db-c071aa5f344d --integration-id 152564
